

-- DROP DATABASE IF EXISTS ejercicio2;
CREATE DATABASE ejercicio2;
USE ejercicio2;

CREATE TABLE senderosmedios (
  ID VARCHAR(20) PRIMARY KEY,
  NOMBRE VARCHAR(100),
  DISTANCIA INTEGER(50),
  DIFICULTAD VARCHAR(30),
  MUNICIPIO VARCHAR(200)
  
);